title: Olá, eu sou Edgar Ferreira!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.edgar-ferreira.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Edgar Ferreira # add your name
author-img: david-freeman.jpg # add your photo
about-author: Com foco na compreensão dos valores e objetivos dos meus clientes, ajudo-os a visualizar melhor suas necessidades, através de metodologias UX podemos alinhar seus objetivos de negócios e usuários, sem perder tempo e recursos valiosos. # add description
social-twitter: EdgarFahrenheit # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: zzedgat2012 # add your Github handle
social-linkedin: efsn88 # add your Linkedin handle
social-email: contato@edgar-ferreira.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
